apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      labels:
        app: my-webapp
    spec:
      containers:
      - name: my-webapp
        image: your-account-id.dkr.ecr.your-region.amazonaws.com/my-webapp:latest
        ports:
        - containerPort: 8080
