apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp
  namespace: my-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      labels:
        app: my-webapp
    spec:
      containers:
      - name: my-webapp
        image: 741448935198.dkr.ecr.ap-northeast-3.amazonaws.com/my-webapp:latest
        ports:
        - containerPort: 8080
